server:
    port: 8890

eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

spring:
    config:
        import: optional:configserver:http://localhost:8888